### ISSUE TITLE
Boss shooting arrows spams 100+ arrows and crashes server.

### ISSUE THREAD

**Issue by jacksmack101** [garbagemule/MobArena#171]
I'm working with waves and the boss wave now crashes the server.
![Screen Shot 2013-03-22 at 2 10 42 AM](https://f.cloud.github.com/assets/2130473/289778/8ae598b6-92c4-11e2-98f7-e98027d8c06c.png)
![Screen Shot 2013-03-22 at 2 39 52 AM](https://f.cloud.github.com/assets/2130473/289779/910fbcd0-92c4-11e2-915a-9ad09b9e6d5c.png)

This is my waves section of my config...

```
    waves:
        recurrent:
            def1:
                type: default
                priority: 1
                frequency: 1
                monsters:
                    zombies: 10
                    skeletons: 10
                    spiders: 10
                    creepers: 10
                    zombie-pigmen: 10
            spec1:
                type: special
                priority: 2
                frequency: 4
                monsters:
                    powered-creepers: 10
                    zombie-pigmen: 10
                    big-slimes: 10
                    blazes: 10
        single:
            swarm1:
                type: swarm
                wave: 6
                monster: slime
                amount: medium
            boss1:
                type: boss
                wave: 7
                monster: cave_spider
                health: low
                abilities: arrows, root-target, throw-nearby
            boss2:
                type: boss
                wave: 14
                monster: magmacube_huge
                health: medium
                abilities: root-target,fire-aura,disorient-target
            boss3:
                type: boss
                wave: 21
                monster: ghast
                health: low
                abilities: fireballs,warp-to-player,chain-lightning
```
