### ISSUE TITLE
Items with Lore: Request - More than just Class Chests

### ISSUE THREAD

**Issue by acstache** [garbagemule/MobArena#212]
Currently, the only items to have Lore saved on them consistently is anything in the Class Chests. There is no way to provide new Lore items through Supply or Upgrade waves, or even through Containers. Containers you can do once, but then you'll have to redo the lore on the items, as they get restored without it. Class Chests get the job done in shorter arena runs, but in longer runs, Class Chests alone may not cut it for some.

This was brought to my attention by Chalkie on the IRC channel

**Comment by garbagemule** [comment]
I think I have come up with a way to fit this feature into the Things API, and it might be possible to make this third-party friendly such that other plugins can write integrations that extend the syntax. Here's a rundown of how I figure this should work and what immediate limitations I see in it. I would _very much_ love some feedback from the community on this since it's such a long-standing request. I also include some development notes for myself or whoever might eventually implement this.

Conversely, since this _is_ a long-standing request, I imagine people may have come up with workarounds. Would my proposed solution replace those workarounds, or are they still necessary, and if so, can we build upon this proposal to remove your workarounds?

## Implementation details
We introduce a new file, `things.yml`, which consists of extended Thing definitions. Here's an example of what I think it might look like:
```yml
lion_slicer:
  type: diamond_sword
  enchantments:
  - sharpness 2
  - sweeping 3
  - unbreaking 3
  name: Lion Slicer
  lore:
  - An ancient blade crafted by expert
  - blacksmiths of the Lionbane Tribe.
  - Powerful and durable.

bladecatcher:
  type: shield
  enchantments:
  - unbreaking 3
  base-color: red
  name: Bladecatcher
  lore:
  - A worn tower shield covered in
  - dents and scratches. It has seen
  - many battles.
```

I hope the syntax is self-explanatory. Note that the shield has a `base-color` property, allowing for some additional per-type customization. I imagine this will require some maintenance, but I think that's fine, especially if we can drop support for ancient Minecraft versions like 1.8 and 1.12.

This file would then get parsed on load and reload, and any references to the items in the config-file would then be resolved to those items:
```yml
classes:
  Knight:
    items: lion_slicer, potion:instant_heal:3
    armor: [...]
  Tank:
    items: stone_sword, bladecatcher, potion:instant_heal:2
    armor: [...]
```

## Limitations
There is one pretty stark limitation, and that's the rigid nature of these references. If we want two Bladecatchers, we wouldn't be able to do `bladecatcher:2`, because the item is parsed/resolved from the entry in `things.yml`, and then it is no longer an "item" but a "thing", and changing those post-parse is not currently possible with how the Things API is structured. We would have to define a second entry in `things.yml`:
```yml
bladecatcher_2:
  type: shield
  amount: 2
  [...]
```

I personally think this is fine. I imagine most of the use cases revolve around single items, so I think it's a fair limitation to impose. It might be possible to work around it, but I don't currently have a good idea how.

Another limitation is one that comes along with the maintenance aspect: the kind of item-specific parsing alluded to by the shield base color would have to be implemented for every "special" item in the game, which means an update would likely be required if a new special item is introduced in a Minecraft update. This is sorta kinda similar to how stuff like angry bees aren't possible until we make an update to the plugin. There is no elegant, robust, guaranteed generic way to be forward-compatible in that regard, so I also personally think it's fine. Besides, once the framework has been wired up, adding new item specifications should be fairly easy, so other people could contribute, which I think is a huge win.

## Development notes
The ThingParser interface is extended with a `parse(ConfigurationSection)` or `parse(Map<String, ?>)` method with a default implementation that just returns `null`. This allows us to make this kind of extension for _any_ Thing, not just items, and thus for other plugins to join along.

On load/reload, the `things.yml` file is read, and each section is passed to the ThingManager via the new method so it can resolve the Things, which are then stored somewhere, maybe just directly in the ThingManager along with their _key_, which in the above examples would be `lion_slicer` and `bladecatcher`. The YAML spec guarantees unique keys with the proposed structure.

When strings are parsed via the ThingManager/ThingParser around the code base, all of them will potentially support these extended Things as long as the ThingManager makes a lookup based on the provided key. This is where the amount limitation mentioned above comes in: even if we split the string by colons like we do elsewhere, passing the amount portion down into the Thing itself is awkward because it doesn't necessarily make any sense for all Things - you wouldn't type `$5:2` to reward ten bucks, you would type `$10`, and permissions don't make sense in multiples either.
