### ISSUE TITLE
Be able to tweak the interval until next wave, per wave basis. 

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#261]
Example being from wave 1 to wave 2, it takes 30 seconds. From wave 2 to wave 3, it takes 20 seconds. From wave 3 to wave 4, 15 seconds, etc. Being able to configure the max time for each wave until the next one appears.

Alternatively, early waves take 10 seconds before the next wave and slowly increment 10% as the wave  number and growth increases. So by wave 100, they may be fighting 200 mobs and need more than 10 seconds before wave 101 begins.

**Comment by WolfieWaffle** [comment]
Wait, I didn't see this, I suggested this on another issue you opened. Either way, I support this.

**Comment by garbagemule** [comment]
Let's have some suggestions as to how this would look in the config-file. Concise and consistent with the rest of the config-file setup.

**Comment by mibby** [comment]
Just throwing around some ideas. I think this could go one of two ways. 

---
Add a ```increment-wave-interval: true/false``` setting with another being something like ```increment-wave-interval-amount: #```. Have it accept a number (in seconds) to increase every wave or a percentage value.

If it is a number; wave interval + [amount x (wave number - 1)]
Minus 1 to calculate accurate increment from wave 2 onward.
```
      wave-interval: 15
      increment-wave-interval: true
      increment-wave-interval-amount: 5
```

* Wave 1 - given 15 seconds to clear before next one is force started. (Uses the starting wave-interval number BEFORE calculating the increment. That begins from wave 2 onward.)
* Wave 2 - given 20 seconds to clear before next one is force started.
* Wave 3 - given 25 seconds to clear before next one is force started.
* Wave 4 - given 30 seconds to clear before next one is force started.
* Wave 5 - given 35 seconds to clear before next one is force started.
* Wave 6 - given 40 seconds to clear before next one is force started.
* Wave 7 - given 45 seconds to clear before next one is force started.
* Wave 8 - given 50 seconds to clear before next one is force started.
* Wave 9 - given 55 seconds to clear before next one is force started.
* Wave 10 - given 60 seconds to clear before next one is force started.
* Wave 100 - given 515 seconds to clear before next one is force started.

This should hopefully give players more time to fight as the waves get harder and denser with mobs until the next round begins / is forced upon them. 

If it is a percentage; calculate (previous wave time x percentage) + previous wave time.
Start increment from wave 2 onward.

```
      wave-interval: 15
      increment-wave-interval: true
      increment-wave-interval-amount: 10%
```

And of course, respect all clear-before-x settings to allow for waves to be completely paused until cleared before the next begins.

---

ALTERNATIVELY, add ```wave-interval: #``` to the wave specific settings. Have it override the default ```wave-interval: #``` general setting if one is found for that specific wave. That way you could have specific waves take longer or shorter amounts of time.

```
    waves:
      recurrent:
        upgrade1:
          priority: 5
          type: upgrade
          wave: 11
       ***wave-interval: 5***
          frequency: 10
          upgrades:
            All: potion:16421:1
            Assassin: arrow:64
            Cleric: potion:16417:2
            Chemist: potion:16425:3, potion:16387:3, potion:8226:1
            Chef: 19321
          give-all-items: true
        normal1:
          type: default
          growth: 0.8
          priority: 1
          frequency: 1
       ***wave-interval-growth: 0.5*** (to grow with the mob growth?)
          monsters:
            zombies: 3
            spiders: 2
      single:
        swarm1:
          priority: 6
          type: swarm
          wave: 5
       ***wave-interval: 15***
          monster: zombie_pigman
          amount: low
        boss1:
          priority: 6
          type: boss
          wave: 10
       ***wave-interval: 60***
          name: Batman
          monster: cave_spider
          health: 300
          abilities: arrows, fireballs, throw-nearby, disorient-nearby
          ability-interval: 20
```
