### ISSUE TITLE
A boss potions question

### ISSUE THREAD

**Issue by Daisywhile** [garbagemule/MobArena#316]
```
    boss6:
      type: boss
      wave: 60
      monster: wither_skeleton
      name: §0Wither_skeleton
      health: 800
      reward: diamond:3
      drops: potion:16428:5, potion:16385:5, cobblestone:10, tnt:15, arrow:64
      potions: speed:1, resistance:0, strength:3
      abilities: warp-to-player, pull-nearby, obsidian-bomb, fireballs
      abilitie-interval: 2
```

but resistance and strength can't use.

[MobArena] Failed to parse potion effect : strength:3
[MobArena] Failed to parse potion effect : resistance:0

why?
