### ISSUE TITLE
Error: Fix it, then run /ma load

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#488]
MobArena compiled as of commit https://github.com/garbagemule/MobArena/commit/548d8c7e4fe670e857f27c9b484f897e6f38df77

What am I suppose to fix? :( 

```
[18:27:33] [Server thread/INFO]: [MobArena] Enabling MobArena v0.102.1-SNAPSHOT
[18:27:33] [Server thread/INFO]: [MobArena] Vault found; economy rewards enabled.
[18:27:33] [Server thread/ERROR]: [MobArena] Fix it, then run /ma load
```

**Comment by garbagemule** [comment]
Hah, the /ma load part is probably due to a refactor action in IntelliJ overreaching.

Anyway, there will be more in the log if this is properly compiled and loaded. That message literally cannot be printed unless there is a message before it. Check the source code in MobArena.java.

**Comment by mibby** [comment]
@garbagemule 


It seems reloading in-game does output what is wrong. 
``` Failed to parse wave growth for wave normal1 of arena default: 2```

```
        normal1:
          type: default
          growth: 2
          priority: 1
          frequency: 1
          monsters:
            zombies: 3
            spiders: 3
```

Is growth no longer a feature? I can't find what is wrong with it.
