### ISSUE TITLE
Default class still requires players to pick a class before they can ready up.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#523]
MobArena discord test build 02/16/2019
Paper dev 570 (Spigot 1.13.2)

@garbagemule I only have a single class configured in my MobArena since I've been toying around with the idea of players upgrading their class by purchasing items as they survive more waves. 

I noticed that when I join the lounge and ready up by hitting the iron block, it states I must first choose a class. However I have it configured so players should automatically start with the default class configured already.

```
classes:
  Empty:
    classchest: 426,78,153,0.0,0.0,void
arenas:
  default:
      default-class: Empty
    class-limits:
      Empty: 99
```

I also noticed that if the class limit is set to 0 (effectively unlimited), when I type ``/ma class empty``, it states there is no more room. I set it to 99 to effectively disable the limit.
