### ISSUE TITLE
Upgrade waves - choose item slot for each item

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#547]
# Feature request
**Short description**
We can already replace armour in upgrade waves, how about we can replace anything?

**Implementation details**
Each inventory slot has a assaign number 0-1-2-3 etc, i'm not too sure what is what. But it should be easy to figure out. Lets pretend 0 is the first slot to the left.
Config example:
```
upgrade1:
          type: upgrade
          wave: 5
          upgrades:
            Gladiator:
              item: iron_sword:1
                slot: 0
              armor: diamond_chestplate, diamond_boots
```
This would make it replace whatever the player has in slot 1.

Hopefully this makes it in a future update! :)
