### ISSUE TITLE
"Missing Feature" Effects in upgrade waves for classes.

### ISSUE THREAD

**Issue by the-red-soul** [garbagemule/MobArena#565]
# Feature request

Implimenting the effects feature with upgrade waves

**Short description**

**Implementation details**

Gives classes updated potion effects when the upgrade wave is reached.

**Additional info**

It is a missing feature listed on the wiki and whatnot.

Any instances of effects in any upgrade waves does not actually work. If in the class file you designate say, Tank class to have health boost, and then on wave 2 have it so the class gains either health boost 2, or a completely different effect, it is ignored completely and no effect is gained or upgraded.

```
upgrade1:
  type: upgrade
  wave: 2
  upgrades:
    all:
      items: potion:instant_heal:6
      effects: strength
upgrade2:
  type: upgrade
  wave: 3
  upgrades:
    all:
      items: potion:instant_heal:6
      effects: strength:1, fast_digging
```

In this config the effect of all classes is to gain strength, and then increase strengths strength, and also gain haste for attack speed. However this is not the case. It is simply ignored with no errors being thrown.
