### ISSUE TITLE
Polar Bears in Swarm wave have 1 HealthPoint

### ISSUE THREAD

**Issue by Ferocimo** [garbagemule/MobArena#618]
**Short description**
```
      single:
        swarm1:
          type: swarm
          wave: 6
          monster: polar_bear
          amount: medium
```
In an arena with a wave like this, polar bears will all have only one HP.

**Details**

* **MobArena version**: 0.104.2
* **Server version**: git-Paper-229 MC 1.15.2

Thank you.
