### ISSUE TITLE
More flexibility with Things in different types of waves

### ISSUE THREAD

**Issue by Maroon28** [garbagemule/MobArena#681]
# Feature request

**Short description**

Essentially, the current way drops work in some of the waves is very limiting. For example, we can only drop items in boss waves, which throws out most of the potential! My idea is to allow Permissions, Economy Money, and Commands to be able to run in supply waves, boss waves, and really anything with `drops:` in it!

**Implementation details**

Not much has to be changed, we'd set it up the same way we set rewards. So, an example would be this:
``` 
       boss1:
          type: boss
          wave: 12
          monster: zombie
          health: medium
          abilities: pull-nearby, disorient-nearby
          ability-interval: 5
          effects: glowing:1, increase_damage:1, slow:0
          drops: cmd:/mobcoins add <player> 50
```

**Additional info**

Thats it!
