### ISSUE TITLE
upgrade-waves: "all" should be handled before specific classes

### ISSUE THREAD

**Issue by sepulzera** [garbagemule/MobArena#700]
# Bug report

**Short description**

I have an upgrade-wave, that will give "all" healing-potions. For a very specific class, I want do remove these potions again.

**Reproduction steps**

```yml
        upgrade2:
          type: upgrade
          wave: 2
          upgrades:
            all: potion:instant_heal:2
            FooClass:
              items: cmd:/clear <player> potion
```

1. Setup an arena with above upgrade-wave.
2. Join the arena with /ma join.
3. Pick FooClass.
4. Get to wave 2.

* Expected: After wave 2, you don't have any potion, as they were removed.
* Actual: You have 2 potions.

**Details**

* **MobArena version**: 0.106
* **Server version**: Paper 1.16.5-786

**Comment by Maroon28** [comment]
The command itself looks wrong anyways (at least on my server). Try doing `cmd:/effect clear <player>` instead and see if that does the trick?

**Comment by sepulzera** [comment]
The command works perfectly fine.

```yml
classes:
  FooClass:
    items: potion:instant_heal:2
[...]
        upgrade2:
          type: upgrade
          wave: 2
          upgrades:
            FooClass:
              items: cmd:/clear <player> potion
```

... will remove both potions on the second wave.
