### ISSUE TITLE
Add the ability to utilize random wave selections

### ISSUE THREAD

**Issue by Roselynnn** [garbagemule/MobArena#795]
**Short description**
Add an option to the wave settings, such as rand: yes/no, to allow for the wave selector to randomize what wave appears based on a given list of rand enabled waves or boss waves.

**Implementation details**
When you are configuring the waves of an arena, you can add a line such as rand: true to have the plugin index the wave as a possibility. 
I.e

```
      recurrent:
        def1:
          type: swarm
          priority: 1
          frequency: 1
          rand: true
          monster: drowned
          effects: fire_resistance
          amount: high
        def2:
          type: default
          frequency: 1
          priority: 1
          rand: true
          monsters:
            guardians: 5
          effects: fire_resistance
```

in this case, there would be a 50/50 split between what type of wave is going to spawn each time.

If there are multiple configured bosses, it could also be enabled to randomize which boss spawns every boss wave, in this case its wave 10.

```
        boss1:
          type: boss
          wave: 10
          priority: 7
          frequency: 10
          rand: true
          monster: wither
          health: low
          abilities: disorient-nearby, shuffle-positions, pull-target, root-target,
            obsidian-bomb
          ability-interval: 15
        boss2:
          type: boss
          wave: 10
          priority: 7
          frequency: 10
          rand: true
          monster: blaze
          health: low
          abilities: obsidian-bomb, disorient-nearby, shuffle-positions, living-bomb,
            fireballs
          ability-interval: 15
        boss3:
          type: boss
          wave: 10
          priority: 7
          frequency: 10
          rand: true
          monster: magma_cube
          health: low
          abilities: living-bomb, root-target, throw-nearby, fire-aura
          ability-interval: 15
```
Since there are 3 bosses, each boss has a 33.33333.... chance of spawning anytime there is a boss wave.

**Additional info**
I'm not sure how it would be configured on the backend, but being able to determine _when_ a wave can spawn, but also randomize it _after that point_ would be helpful as well. 

i.e
```
        swarm1:
          type: swarm
          priority: 1
          frequency: 6
          wave: 5
          rand: true
          monster: wither_skeleton
          amount: medium
```
          
Would start on wave 5 and then be put into the rand pool with other waves. It would provide a unique way of scaling difficulty and adding more variety the longer a player is in an arena. 

End-User wise, having it be included in wave setup rather than an arena-global setting is a lot more customizable, but I'm not entirely sure how the wave handler is configured to work.

p.s it would also be neat to be able to name bosses and waves as a wave setting option.
